trigger:
  batch: true
  branches:
    include:
    - master
    
resources:
- repo: self

pool:
  vmImage: ubuntu-16.04
  demands: npm

steps:
- task: NodeTool@0
  displayName: 'Use Node'
  inputs:
    versionSpec: 11.x
    checkLatest: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- powershell: node convert.js $(Build.ArtifactStagingDirectory)/png
  displayName: 'PowerShell Script'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(Build.ArtifactStagingDirectory)/png 
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/jams.zip' 
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/png/jams.zip'
    artifactName: drop